version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=dpg-ct3br7lumphs73dr1d70-a
      - DB_PORT=5432
      - DB_DATABASE=login_system_66lz
      - DB_USERNAME=login_system_66lz_user
      - DB_PASSWORD=WYW5f81ukbXhZzlPbRM836gEdtpkxHpO  

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: WYW5f81ukbXhZzlPbRM836gEdtpkxHpO
      MYSQL_DATABASE: login_system_66lz
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
